name: Deploy AWS Support System

# This workflow runs only when code is pushed to the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install dependencies
      - name: Install dependencies
        working-directory: src/functions/ticket-processor
        run: npm install

      # Package application
      - name: Package application
        run: |
          aws cloudformation package \
            --template-file infrastructure/support-system.yaml \
            --s3-bucket jiva-support-system-2025 \
            --output-template-file packaged.yaml

      # Deploy to AWS
      - name: Deploy to AWS
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name support-system \
            --capabilities CAPABILITY_IAM
